/*
    JSDL - Java(TM) interface to SDL
    Copyright (C) 2001  Steven Hugg

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Steven Hugg
    hugg@pobox.com
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fasterlight_sdl_event_SDLEventQueue */

#ifndef _Included_com_fasterlight_sdl_event_SDLEventQueue
#define _Included_com_fasterlight_sdl_event_SDLEventQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fasterlight_sdl_event_SDLEventQueue
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fasterlight_sdl_event_SDLEventQueue_isEmpty
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_event_SDLEventQueue
 * Method:    poll
 * Signature: ()Lcom/fasterlight/sdl/event/SDLEvent;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_event_SDLEventQueue_poll
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_event_SDLEventQueue
 * Method:    pump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_event_SDLEventQueue_pump
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_event_SDLEventQueue
 * Method:    waitForEvent
 * Signature: ()Lcom/fasterlight/sdl/event/SDLEvent;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_event_SDLEventQueue_waitForEvent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
