/*
    JSDL - Java(TM) interface to SDL
    Copyright (C) 2001  Steven Hugg

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Steven Hugg
    hugg@pobox.com
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_fasterlight_sdl_video_SDLSurface.h"
#include "JSDL.h"
#include <stdlib.h>

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    blit
 * Signature: (Lcom/fasterlight/sdl/SDLRect;Lcom/fasterlight/sdl/SDLSurface;Lcom/fasterlight/sdl/SDLRect;)V
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_video_SDLSurface_blit
  (JNIEnv *env, jobject jdestsurf, jobject jdestrect, jobject jsrcsurf, jobject jsrcrect)
{
	SDL_Surface* src;
	SDL_Surface* dest;
	SDL_Rect srcrect, destrect;
	SDL_Rect* srect = NULL;
	SDL_Rect* drect = NULL;
	int result;

	JSDL_GetSurface(jsrcsurf, &src);
	JSDL_GetSurface(jdestsurf, &dest);
	if (jsrcrect != NULL)
	{
		JSDL_GetRect(jsrcrect, &srcrect);
		srect = &srcrect;
	}
	if (jdestrect != NULL)
	{
		JSDL_GetRect(jdestrect, &destrect);
		drect = &destrect;
	}

	return SDL_BlitSurface(src, srect, dest, drect);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    convert
 * Signature: (Lcom/fasterlight/sdl/SDLPixelFormat;I)Lcom/fasterlight/sdl/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_video_SDLSurface_convert
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    convertForDisplay
 * Signature: ()Lcom/fasterlight/sdl/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_video_SDLSurface_convertForDisplay
  (JNIEnv *env, jobject jsurf)
{
	SDL_Surface* surf;
	JSDL_GetSurface(jsurf, &surf);
	surf = SDL_DisplayFormat(surf);
	JSDL_ASSERT(surf != NULL);
	return JSDL_NewSurface(env, surf);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    createRGBSurface
 * Signature: (IIIIIIII)Lcom/fasterlight/sdl/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_video_SDLSurface_createRGBSurface
  (JNIEnv *env, jclass clazz, jint flags, 
  	jint width, jint height, jint depth, 
  	jint rmask, jint gmask, jint bmask, jint amask)
{
	SDL_Surface* surf;
	surf = SDL_CreateRGBSurface(flags, width, height, depth, rmask, gmask,
		bmask, amask);
	JSDL_ASSERT(surf != NULL);
	return JSDL_NewSurface(env, surf);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    createRGBSurfaceFrom
 * Signature: ([IIIIIIII)Lcom/fasterlight/sdl/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_video_SDLSurface_createRGBSurfaceFrom
  (JNIEnv *env, jclass clazz, jintArray jbytes, 
  	jint width, jint height, jint depth, jint pitch,
  	jint rmask, jint gmask, jint bmask, jint amask)
{
	SDL_Surface* surf;
	jint* bytes;
	bytes = (*env)->GetIntArrayElements(env, jbytes, NULL);
	surf = SDL_CreateRGBSurfaceFrom((void*)bytes, width, height, depth, pitch, 
		rmask, gmask, bmask, amask);
	(*env)->ReleaseIntArrayElements(env, jbytes, bytes, 0);
	JSDL_ASSERT(surf != NULL);
	return JSDL_NewSurface(env, surf);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    fillRect
 * Signature: (Lcom/fasterlight/sdl/SDLRect;I)V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_fillRect
  (JNIEnv *env, jobject jsurf, jobject jrect, jint color)
{
	SDL_Rect rect;
	SDL_Surface* surf;
	
	JSDL_GetRect(jrect, &rect);
	JSDL_GetSurface(jsurf, &surf);
	SDL_FillRect(surf, &rect, color);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    flip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_flip
  (JNIEnv *env, jobject jsurf)
{
	SDL_Surface *surf;
	JSDL_GetSurface(jsurf, &surf);
	JSDL_ASSERT(SDL_Flip(surf) == 0);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_free
  (JNIEnv *env, jobject jsurf)
{
	SDL_Surface *surf;
	JSDL_GetSurface(jsurf, &surf);
	if (surf == NULL)
		return; /* already freed, return */
	SDL_FreeSurface(surf);
	JSDL_SetIntField(jsurf, "_sdlsurf", 0);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    loadBMP
 * Signature: (Ljava/lang/String;)Lcom/fasterlight/sdl/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_video_SDLSurface_loadBMP
  (JNIEnv *env, jclass clazz, jstring jfilename)
{
	const jbyte* str;
	SDL_Surface* surf;
	
	str = (*env)->GetStringUTFChars(env, jfilename, NULL);
	JSDL_ASSERT(str != NULL);
	surf = SDL_LoadBMP(str);
	(*env)->ReleaseStringUTFChars(env, jfilename, str);
	JSDL_ASSERT(surf != NULL);
	return JSDL_NewSurface(env, surf);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_lock
  (JNIEnv *env, jobject jsurf)
{
	SDL_Surface *surf;
	JSDL_GetSurface(jsurf, &surf);
	JSDL_ASSERT(SDL_LockSurface(surf) == 0);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    saveBMP
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_saveBMP
  (JNIEnv *env, jobject jsurf, jstring jfilename)
{
	const jbyte* str;
	SDL_Surface* surf;
	int res;
	
	str = (*env)->GetStringUTFChars(env, jfilename, NULL);
	JSDL_ASSERT(str != NULL);
	JSDL_GetSurface(jsurf, &surf);
	res = SDL_SaveBMP(surf, str);
	(*env)->ReleaseStringUTFChars(env, jfilename, str);
	JSDL_ASSERT(res == 0);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    setAlpha
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_setAlpha
  (JNIEnv *env, jobject jsurf, jint flag, jbyte alpha)
{
	SDL_Surface* surf;
	
	JSDL_GetSurface(jsurf, &surf);
	JSDL_ASSERT(SDL_SetAlpha(surf, flag, alpha) == 0);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    setClipping
 * Signature: (Lcom/fasterlight/sdl/SDLRect;)V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_setClipping
  (JNIEnv *env, jobject jsurf, jint x1, jint y1, jint x2, jint y2)
{
	SDL_Surface* surf;
	SDL_Rect rect;
	
	JSDL_GetSurface(jsurf, &surf);
	rect.x = x1;
	rect.y = y1;
	rect.w = (x2-x1);
	rect.h = (y2-y1);
	SDL_SetClipRect(surf, &rect);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    setColorKey
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_setColorKey
  (JNIEnv *env, jobject jsurf, jint flag, jint key)
{
	SDL_Surface* surf;
	
	JSDL_GetSurface(jsurf, &surf);
	JSDL_ASSERT(SDL_SetColorKey(surf, flag, key) == 0);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    setColors
 * Signature: ([Lcom/fasterlight/sdl/SDLColor;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fasterlight_sdl_video_SDLSurface_setColors
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    unlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_unlock
  (JNIEnv *env, jobject jsurf)
{
	SDL_Surface *surf;
	JSDL_GetSurface(jsurf, &surf);
	JSDL_ASSERT(SDL_LockSurface(surf) == 0);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_update__
  (JNIEnv *env, jobject jsurf)
{
	SDL_Surface* surf;
	
	JSDL_GetSurface(jsurf, &surf);
	SDL_UpdateRect(surf, 0, 0, 0, 0);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    update
 * Signature: (Lcom/fasterlight/sdl/SDLRect;)V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_update__Lcom_fasterlight_sdl_video_SDLRect_2
  (JNIEnv *env, jobject jsurf, jobject jrect)
{
	SDL_Rect rect;
	SDL_Surface* surf;
	
	JSDL_GetRect(jrect, &rect);
	JSDL_GetSurface(jsurf, &surf);
	SDL_UpdateRect(surf, rect.x, rect.y, rect.w, rect.h);
}

/*
 * Class:     com_fasterlight_sdl_video_SDLSurface
 * Method:    update
 * Signature: ([Lcom/fasterlight/sdl/SDLRect;)V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLSurface_update___3Lcom_fasterlight_sdl_video_SDLRect_2
  (JNIEnv *env, jobject jsurf, jobjectArray jrects)
{
	SDL_Surface* surf;
	SDL_Rect* rects;
	int l,i;
	
	JSDL_GetSurface(jsurf, &surf);
	l = (*env)->GetArrayLength(env, jrects);
	rects = (SDL_Rect*)malloc(sizeof(SDL_Rect)*l);
	for (i=0; i<l; i++)
	{
		jobject jrect = (*env)->GetObjectArrayElement(env, jrects, i);
		JSDL_GetRect(jrect, rects+i);
		(*env)->DeleteLocalRef(env, jrect);
	}
	SDL_UpdateRects(surf, l, rects);
	free(rects);
}
