/*
    JSDL - Java(TM) interface to SDL
    Copyright (C) 2001  Steven Hugg

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Steven Hugg
    hugg@pobox.com
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fasterlight_sdl_video_SDLVideoInfo */

#ifndef _Included_com_fasterlight_sdl_video_SDLVideoInfo
#define _Included_com_fasterlight_sdl_video_SDLVideoInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef com_fasterlight_sdl_video_SDLVideoInfo_HW_AVAILABLE
#define com_fasterlight_sdl_video_SDLVideoInfo_HW_AVAILABLE 1L
#undef com_fasterlight_sdl_video_SDLVideoInfo_WM_AVAILABLE
#define com_fasterlight_sdl_video_SDLVideoInfo_WM_AVAILABLE 2L
#undef com_fasterlight_sdl_video_SDLVideoInfo_BLIT_HW
#define com_fasterlight_sdl_video_SDLVideoInfo_BLIT_HW 1024L
#undef com_fasterlight_sdl_video_SDLVideoInfo_BLIT_HW_CC
#define com_fasterlight_sdl_video_SDLVideoInfo_BLIT_HW_CC 2048L
#undef com_fasterlight_sdl_video_SDLVideoInfo_BLIT_HW_A
#define com_fasterlight_sdl_video_SDLVideoInfo_BLIT_HW_A 4096L
#undef com_fasterlight_sdl_video_SDLVideoInfo_BLIT_SW
#define com_fasterlight_sdl_video_SDLVideoInfo_BLIT_SW 8192L
#undef com_fasterlight_sdl_video_SDLVideoInfo_BLIT_SW_CC
#define com_fasterlight_sdl_video_SDLVideoInfo_BLIT_SW_CC 16384L
#undef com_fasterlight_sdl_video_SDLVideoInfo_BLIT_SW_A
#define com_fasterlight_sdl_video_SDLVideoInfo_BLIT_SW_A 32768L
#undef com_fasterlight_sdl_video_SDLVideoInfo_BLIT_FILL
#define com_fasterlight_sdl_video_SDLVideoInfo_BLIT_FILL 65536L
#ifdef __cplusplus
}
#endif
#endif
