/*
    JSDL - Java(TM) interface to SDL
    Copyright (C) 2001  Steven Hugg

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Steven Hugg
    hugg@pobox.com
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fasterlight_sdl_video_SDLVideo */

#ifndef _Included_com_fasterlight_sdl_video_SDLVideo
#define _Included_com_fasterlight_sdl_video_SDLVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fasterlight_sdl_video_SDLVideo
 * Method:    getVideoInfo
 * Signature: ()Lcom/fasterlight/sdl/video/SDLVideoInfo;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_video_SDLVideo_getVideoInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_video_SDLVideo
 * Method:    getVideoModes
 * Signature: (Lcom/fasterlight/sdl/video/SDLPixelFormat;I)[Lcom/fasterlight/sdl/video/SDLVideoMode;
 */
JNIEXPORT jobjectArray JNICALL Java_com_fasterlight_sdl_video_SDLVideo_getVideoModes
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_fasterlight_sdl_video_SDLVideo
 * Method:    getVideoSurface
 * Signature: ()Lcom/fasterlight/sdl/video/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_video_SDLVideo_getVideoSurface
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_video_SDLVideo
 * Method:    internalInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_video_SDLVideo_internalInit
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_video_SDLVideo
 * Method:    isVideoModeOK
 * Signature: (Lcom/fasterlight/sdl/video/SDLVideoMode;)I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_video_SDLVideo_isVideoModeOK
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_fasterlight_sdl_video_SDLVideo
 * Method:    setVideoMode
 * Signature: (Lcom/fasterlight/sdl/video/SDLVideoMode;)Lcom/fasterlight/sdl/video/SDLSurface;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_video_SDLVideo_setVideoMode
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
