/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fasterlight_sdl_timer_SDLTimer */

#ifndef _Included_com_fasterlight_sdl_timer_SDLTimer
#define _Included_com_fasterlight_sdl_timer_SDLTimer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: sdl_init_time */
/*
 * Class:     com_fasterlight_sdl_timer_SDLTimer
 * Method:    getTicks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_timer_SDLTimer_getTicks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
