/*
    JSDL - Java(TM) interface to SDL
    Copyright (C) 2001  Steven Hugg

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Steven Hugg
    hugg@pobox.com
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fasterlight_sdl_joystick_SDLJoystick */

#ifndef _Included_com_fasterlight_sdl_joystick_SDLJoystick
#define _Included_com_fasterlight_sdl_joystick_SDLJoystick
#ifdef __cplusplus
extern "C" {
#endif
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_CENTERED
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_CENTERED 0L
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_UP
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_UP 1L
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_RIGHT
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_RIGHT 2L
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_DOWN
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_DOWN 4L
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_LEFT
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_LEFT 8L
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_RIGHTUP
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_RIGHTUP 3L
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_RIGHTDOWN
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_RIGHTDOWN 6L
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_LEFTUP
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_LEFTUP 9L
#undef com_fasterlight_sdl_joystick_SDLJoystick_HAT_LEFTDOWN
#define com_fasterlight_sdl_joystick_SDLJoystick_HAT_LEFTDOWN 12L
/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_close
  (JNIEnv *, jobject);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getAxis
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getAxis
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getBall
 * Signature: (I)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getBall
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getButton
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getButton
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getHat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getHat
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getIndex
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getJoystickName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getJoystickName
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getNumAxes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getNumAxes
  (JNIEnv *, jobject);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getNumBalls
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getNumBalls
  (JNIEnv *, jobject);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getNumButtons
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getNumButtons
  (JNIEnv *, jobject);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getNumHats
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getNumHats
  (JNIEnv *, jobject);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    getNumJoysticks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_getNumJoysticks
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    internalInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_internalInit
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    isOpen
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_isOpen
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    openJoystick
 * Signature: (I)Lcom/fasterlight/sdl/joystick/SDLJoystick;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_openJoystick
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    setEventState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_setEventState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fasterlight_sdl_joystick_SDLJoystick
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_joystick_SDLJoystick_update
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
