/*
    JSDL - Java(TM) interface to SDL
    Copyright (C) 2001  Steven Hugg

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Steven Hugg
    hugg@pobox.com
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_fasterlight_sdl_event_SDLEventQueue.h"
#include "JSDL.h"

/* todo: these are slow */

static jobject JSDL_EventToJEvent(JNIEnv* env, SDL_Event* ev)
{
	jobject jev = NULL;
	switch (ev->type)
	{
		case SDL_ACTIVEEVENT:
			JSDL_NewObject(JSDLPKG "/event/SDLActivationEvent", &jev);
			JSDL_SetBooleanField(jev, "gain", ((SDL_ActiveEvent*)ev)->gain);
			JSDL_SetByteField(jev, "state", ((SDL_ActiveEvent*)ev)->state);
			break;
		case SDL_KEYDOWN:
			JSDL_NewObject(JSDLPKG "/event/SDLKeyDownEvent", &jev);
		case SDL_KEYUP:
			if (jev == NULL)
				JSDL_NewObject(JSDLPKG "/event/SDLKeyUpEvent", &jev);
			JSDL_SetByteField(jev, "scancode", ((SDL_KeyboardEvent*)ev)->keysym.scancode);
			JSDL_SetIntField(jev, "sym", ((SDL_KeyboardEvent*)ev)->keysym.sym);
			JSDL_SetIntField(jev, "mod", ((SDL_KeyboardEvent*)ev)->keysym.mod);
			JSDL_SetCharField(jev, "unicode", ((SDL_KeyboardEvent*)ev)->keysym.unicode);
			break;
		case SDL_MOUSEMOTION:
			JSDL_NewObject(JSDLPKG "/event/SDLMouseMotionEvent", &jev);
			JSDL_SetByteField(jev, "state", ((SDL_MouseMotionEvent*)ev)->state);
			JSDL_SetShortField(jev, "x", ((SDL_MouseMotionEvent*)ev)->x);
			JSDL_SetShortField(jev, "y", ((SDL_MouseMotionEvent*)ev)->y);
			JSDL_SetShortField(jev, "xrel", ((SDL_MouseMotionEvent*)ev)->xrel);
			JSDL_SetShortField(jev, "yrel", ((SDL_MouseMotionEvent*)ev)->yrel);
			break;
		case SDL_MOUSEBUTTONUP:
			JSDL_NewObject(JSDLPKG "/event/SDLMouseButtonUpEvent", &jev);
		case SDL_MOUSEBUTTONDOWN:
			if (jev == NULL)
				JSDL_NewObject(JSDLPKG "/event/SDLMouseButtonDownEvent", &jev);
			JSDL_SetByteField(jev, "state", ((SDL_MouseButtonEvent*)ev)->state);
			JSDL_SetShortField(jev, "x", ((SDL_MouseButtonEvent*)ev)->x);
			JSDL_SetShortField(jev, "y", ((SDL_MouseButtonEvent*)ev)->y);
			JSDL_SetByteField(jev, "button", ((SDL_MouseButtonEvent*)ev)->button);
			break;
		case SDL_QUIT:
			JSDL_NewObject(JSDLPKG "/event/SDLQuitEvent", &jev);
			break;
		default:
			fprintf(stderr, "JSDL: Unknown event type: %d\n", ev->type);
			break;
	}
	if (jev != NULL)
	{
		JSDL_SetByteField(jev, "type", ev->type);
	}
	return jev;
}

/*
 * Class:     com_fasterlight_sdl_event_SDLEventQueue
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fasterlight_sdl_event_SDLEventQueue_isEmpty
  (JNIEnv *env, jclass clazz)
{
	return !(SDL_PollEvent(NULL));
}

/*
 * Class:     com_fasterlight_sdl_event_SDLEventQueue
 * Method:    poll
 * Signature: ()Lcom/fasterlight/sdl/event/SDLEvent;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_event_SDLEventQueue_poll
  (JNIEnv *env, jclass clazz)
{
	SDL_Event ev;
	if (SDL_PollEvent(&ev))
	{
		return JSDL_EventToJEvent(env, &ev);
	} else
		return NULL;
}

/*
 * Class:     com_fasterlight_sdl_event_SDLEventQueue
 * Method:    pump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fasterlight_sdl_event_SDLEventQueue_pump
  (JNIEnv *, jclass);

/*
 * Class:     com_fasterlight_sdl_event_SDLEventQueue
 * Method:    waitForEvent
 * Signature: ()Lcom/fasterlight/sdl/event/SDLEvent;
 */
JNIEXPORT jobject JNICALL Java_com_fasterlight_sdl_event_SDLEventQueue_waitForEvent
  (JNIEnv *, jclass);

